server:
  port: 8763

# IDENTITY
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer3
    preferIpAddress: true
    # 注册服务默认心跳时间为30秒，当一个服务器不可用，需要3个心跳才能让服务器和客户端的元数据相同。在生产环境最好使用默认配置。
    # leaseRenewalIntervalInSeconds: 5

  server:
    #默认值为0.85，当server在15分钟内，比值低于percent，即少了15%的微服务心跳，server会进入自我保护状态
    # renewalPercentThreshold: 0.49
    # 注册服务默认心跳时间为30秒，当一个服务器不可用，需要3个心跳才能让服务器和客户端的元数据相同。在生产环境最好使用默认配置。
    # leaseRenewalIntervalInSeconds: 5

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/